services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5080:5080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5080
      - ConnectionStrings__Db=Host=db;Database=postgres;Username=postgres;Password=postgres
      - Jwt__Issuer=issuer
      - Jwt__Audience=audience
      - Jwt__SecretKey=4d5b7a4ba37911aeddd540be07a70f766bc357f1f2f2a7432a9f7103ef36d1c5
      - Jwt__TokenValidityInMinutes=60
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

